name: Playwright Tests
on:
  push:
    branches: [main]
jobs:
  build-and-test:
    uses: ./.github/workflows/test_and_build.yaml
    with:
      upload-pages-artifact: true

  deploy-to-pages:
    needs: build-and-test
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/configure-pages@v5
      - uses: actions/deploy-pages@v4
        id: deployment
